name: Docker Image Front
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      #checkout / download des sources
      - name: Checkout
        uses: actions/checkout@v4
      #QEMU : conteneur docker fonctionnant sur VM x86 and x64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      #utilisation de dockerbuildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      #Login avec user docker et token généré sur dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #Build et push vers docker
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          #répertoire de travail
          context: ./front
          #fichier dockerfile
          file: front/Dockerfile
          push: true
          #tag composé du user docker et bobapp-front
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest
