name: Tests and Code Coverage Back

#workflow se lance lors d'ub push ou pull_request sur la branche main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        #répertoire de travail
        working-directory: ./back
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      #lance le clean test du back
      - name: Build with Maven
        run: mvn clean test --file pom.xml
      #affiche le status
      - run: echo "🍏Mvn Test's status is ${{ job.status }}."
      #coverage du back
      - name: Add coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          pass-emoji: 🍏
          fail-emoji: ❌
          debug-mode: false
      #affiche le coverage total et du changement
      - run: echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
      - run: echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
      #ajout du résultat du coverage dans git
      - name: Commit Code Coverage Report
        run: |
          git config --global user.email "cedh@posteo.net"
          git config --global user.name "cedh44"
          git add .
          git commit -m "Add jacoco code coverage report"
          git push
