name: Tests and Code Coverage Front

#workflow se lance lors d'une pull_request sur la branche main
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        #répertoire de travail
        working-directory: ./front
    strategy:
      matrix:
        #version de node
        node-version: [16.x]
    steps:
      #checkout / download des sources et utilisation de nodejs
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      #installation des dépendances
      - name: install dependencies
        run: npm install
      #test et coverage du front
      - name: test coverage
        run: npm run test-coverage
      #ajout du résultat du coverage dans git
      - name: Commit Karma Code Coverage Report
        run: |
          git config --global user.email "cedh@posteo.net"
          git config --global user.name "cedh44"
          git fetch
          git checkout develop
          git pull origin develop
          git add coverage/bobapp
          git commit -m "Add Karma code coverage report"
          git push origin develop
      - run: echo "🍏Npm run test-coverage's status is ${{ job.status }}."
