name: Tests and Code Coverage Back

#workflow se lance lors d'une pull_request sur la branche main
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        #répertoire de travail
        working-directory: ./back
    steps:
      #checkout / download des sources et utilisation du jdk11
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      #lance le clean test du back
      - name: Build with Maven
        run: mvn clean test --file pom.xml
      #coverage du back
      - name: Add coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          #couverture minimum du code global attendue : 80%
          min-coverage-overall: 80
          #couverture mininum du code modifié attendue : 80%
          min-coverage-changed-files: 80
          pass-emoji: 🍏
          fail-emoji: ❌
          debug-mode: false
      #affiche le coverage total et du changement
      - run: echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
      - run: echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
      #ajout du résultat du coverage dans git
      - name: Commit Jacoco Code Coverage Report
        run: |
          git config --global user.email "cedh@posteo.net"
          git config --global user.name "cedh44"
          git fetch
          git checkout develop
          git pull origin develop
          git add target/site
          git commit -m "Add Jacoco code coverage report"
          git push origin develop
      #affiche le status à la fin
      - run: echo "🍏Mvn Test's status is ${{ job.status }}."
